### ISSUE TITLE
[Into to iOS] Project 1 - Review my app

### ISSUE THREAD

**Issue by marenas** [marenas/rotten-tomatoes#1]
Here is my progress for the first assignment of the course. /cc @codepathreview

**Comment by nickai** [comment]
:+1: Great work Matias! The point of this homework was to explore a simple example of a full MVC application with a RESTful API. The scroll view moving up and down isn't required, but a nice effect to add. You can see the project feedback guide for some tips on how to achieve this effect.

A few notes after checking out the code:
- Nice code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you can take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
- You should always try to minimize the number of properties and methods in the header files and move all private properties and methods into the class extension (the @interface block in the .m file).
- In a future homework, we will cover how to implement models that can deserialize from an NSDictionary. It might be interesting to check out the [Mantle project](https://github.com/Mantle/Mantle) for a lightweight ORM.
- A good design is to have your custom Movie cell have a property `movie`. In the custom setter of `movie`, you can configure the various labels and images. This decouples your custom cells from the table view controllers.
- Nice work loading the images asynchronously.
- Nice work setting up the proper modes for the images so that they are not stretched.
- Nice work implementing the error message on network failure.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_ios/feedback_guides_objc/project_1_feedback) which covers the most common points we see for this project. Read through the feedback guide point-by-point to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at support@codepath.com.
